services:
  migrate:
    build:
      context: ./apps/server
      dockerfile: Dockerfile.migrate
    restart: "no"
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
    volumes:
      - ./.data/sqlite:/app/data

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8034:8034"
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
    volumes:
      - ./.data/sqlite:/app/data
    depends_on:
      migrate:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - "8383:80"
    depends_on:
      - server
    environment:
      - API_URL=http://localhost:8034

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"
    networks:
      - appnet
