services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--save",
      "",
      "--appendonly",
      "no",
    ]
    ports:
      - "6381:6379"

  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    command:
      - "--redis-addr=redis:6379"
