networks:
  appnet:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DB_NAME:-peekaping}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-peekaping}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  migrate:
    build:
      context: ./apps/server
      dockerfile: infra/Dockerfile.migrate
    restart: "no"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_TYPE=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

  api:
    build:
      context: ./apps/server
      dockerfile: infra/Dockerfile.api
    restart: unless-stopped
    ports:
      - "8034:8034"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_TYPE=postgres
      - REDIS_HOST="redis"
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  producer:
    build:
      context: ./apps/server
      dockerfile: infra/Dockerfile.producer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_TYPE=mongo
      - REDIS_HOST="redis"
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  worker:
    build:
      context: ./apps/server
      dockerfile: infra/Dockerfile.worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST="redis"
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  ingester:
    build:
      context: ./apps/server
      dockerfile: infra/Dockerfile.ingester
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_TYPE=mongo
      - REDIS_HOST="redis"
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - "8383:80"
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:8034
    networks:
      - appnet

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
