services:
  database:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${DB_PORT:-27017}:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./.data/mongodb:/data/db

  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--save",
      "",
      "--appendonly",
      "no",
    ]
    ports:
      - "${REDIS_PORT:-6379}:6379"

  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    command:
      - "--redis-addr=redis:6379"
