services:
  peekaping:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
    restart: unless-stopped
    ports:
      - "8383:8383"
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/peekaping.db
      - API_URL=http://localhost:8383
    volumes:
      - ./.data/sqlite:/app/data
    container_name: peekaping-all-in-one
