name: Build and Push Docker Images Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.2.3)'
        required: true
        type: string
      changelog:
        description: 'Changelog for this release'
        required: true
        type: string

jobs:
  tag-release-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # - name: Create Git tag
      #   run: |
      #     git tag ${{ github.event.inputs.version }}
      #     git push origin ${{ github.event.inputs.version }}

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ github.event.inputs.version }}
      #     body: ${{ github.event.inputs.changelog }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          push: true
          tags: ghcr.io/peekaping-ui:${{ github.event.inputs.version }}

      - name: Build and push Server image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/server
          push: true
          tags: ghcr.io/peekaping-server:${{ github.event.inputs.version }}
