name: Build and Push Docker Images Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.2.3)'
        required: true
        type: string
      changelog:
        description: 'Changelog for this release'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version in package.json (web)
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
        working-directory: ./apps/web

      - name: Update version in main.go (server)
        run: |
          sed -i.bak -E 's/(Version\s*=\s*")[^"]+(")/\1${{ github.event.inputs.version }}\2/' version.go
          rm version.go.bak
        working-directory: ./apps/server/src

      - name: Write version.ts for web
        run: |
          echo "// This file is auto-generated by the release workflow" > src/version.ts
          echo "export const VERSION = \"${{ github.event.inputs.version }}\";" >> src/version.ts
        working-directory: ./apps/web

      - name: Build and push UI image
        id: build_ui
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-web:${{ github.event.inputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-web:latest

      - name: Build and push Server image
        id: build_server
        uses: docker/build-push-action@v5
        with:
          context: ./apps/server
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-server:${{ github.event.inputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-server:latest

      - name: Commit and tag version bump
        run: |
          git add apps/web/package.json apps/web/src/version.ts apps/server/src/version.go
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: |
            ${{ github.event.inputs.changelog }}

            ## Docker Images

            ### GitHub Container Registry (GHCR)
            - UI: `ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:${{ github.event.inputs.version }}` / `ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:latest`
            - Server: `ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:${{ github.event.inputs.version }}` / `ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-server:latest`

            ### Docker Hub
            - UI: `${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-web:${{ github.event.inputs.version }}` / `${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-web:latest`
            - Server: `${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-server:${{ github.event.inputs.version }}` / `${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-server:latest`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
